[build]
  publish = "dist/"
  command = "npm run generate"
  functions = "functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/homes"
  to = "/developments"
  status = 301

[[redirects]]
  from = "/home"
  to = "/developments"
  status = 301

